import { NextResponse } from "next/server";
import { AVAILABLE_TAGS, roles as AVAILABLE_ROLES } from "@/components/Universal-static-storage";
import { generateObject } from "ai";
import { z } from "zod";
import { google } from "@ai-sdk/google";

export async function GET(req: Request) {
  try {
    const { searchParams } = new URL(req.url);
    const query = searchParams.get("query");
    const mode = searchParams.get("mode");

    if (!query || !mode) {
      return NextResponse.json(
        { error: "Missing query or mode" },
        { status: 400 },
      );
    }

    console.log("Query we got at backend:", query);
    console.log("Mode we got at backend:", mode);

    let systemPrompt = "";
    let schema;

    if (mode === "team") {
      schema = z.object({
        tags: z.array(z.enum(AVAILABLE_TAGS as [string, ...string[]])).min(2).max(5)
          .describe("An array of project tags. Minimum 2, maximum 5."),
        roles: z.array(z.enum(AVAILABLE_ROLES as [string, ...string[]]))
          .describe("An array of roles relevant to the search query."),
      });
      systemPrompt = `You are an AI assistant helping to find team roles and tags for a search query. 
      You MUST ONLY choose from the following predefined lists:
      Tags: ${AVAILABLE_TAGS.join(", ")}
      Roles: ${AVAILABLE_ROLES.join(", ")}
      Return between 2 and 5 tags, and any relevant roles for the query: "${query}".`;
    } else if (mode === "projects") {
      schema = z.object({
        tags: z.array(z.enum(AVAILABLE_TAGS as [string, ...string[]]))
          .describe("An array of tags relevant to the search query."),
      });
      systemPrompt = `You are an AI assistant helping to find project tags for a search query.
      You MUST ONLY choose from the following predefined tags: ${AVAILABLE_TAGS.join(", ")}.
      Return tags that are most relevant to the query: "${query}".`;
    } else if (mode === "contribute") {
      schema = z.object({
        tags: z.array(z.enum(AVAILABLE_TAGS as [string, ...string[]]))
          .describe("An array of tags relevant to the search query."),
        roles: z.array(z.enum(AVAILABLE_ROLES as [string, ...string[]])).optional()
          .describe("An array of roles relevant to the search query (optional)."),
      });
      systemPrompt = `You are an AI assistant helping to find tags and optional roles for contributors based on a search query.
      You MUST ONLY choose from:
      Tags: ${AVAILABLE_TAGS.join(", ")}
      Roles: ${AVAILABLE_ROLES.join(", ")}
      Return relevant tags and optionally relevant roles for the query: "${query}".`;
    } else {
      return NextResponse.json({ error: "Invalid mode" }, { status: 400 });
    }

    const { object } = await generateObject({
      model: google("gemini-3-flash-preview"),
      schema: schema,
      prompt: `Query: ${query}`,
      system: systemPrompt,
    });

    console.log("OBJECT generated by AI", object);
    return NextResponse.json(object);

  } catch (error) {
    console.error("Error in AI search:", error);
    return NextResponse.json(
      { error: "Failed to perform AI search" },
      { status: 500 },
    );
  }
}
