export const AVAILABLE_TAGS = [
  "Productivity",
  "AI",
  "Healthcare",
  "Edutech",
  "Fintech",
  "Web3",
  "Agents",
  "SaaS",
  "E-commerce",
  "Social Media",
  "Developer Tools",
  "Open Source",
  "Machine Learning",
  "Data Science",
  "Blockchain",
  "Crypto",
  "DeFi",
  "NFT",
  "Metaverse",
  "Gaming",
  "AR/VR",
  "Mobile App",
  "Web App",
  "Desktop App",
  "CLI",
  "API",
  "Library",
  "Framework",
  "CMS",
  "CRM",
  "Automation",
  "Cybersecurity",
  "Database",
  "Cloud",
  "DevOps",
  "Testing",
  "Monitoring",
  "Analytics",
  "Marketing",
  "SEO",
  "Content",
  "Design",
  "UX/UI",
  "Education",
  "Research",
  "Environment",
  "Sustainability",
  "Non-profit",
  "Community",
];

export const roles = [
    "frontend developer",
    "backend developer",
    "fullstack developer",
    "devops engineer",
    "site reliability engineer (SRE)",
    "cloud engineer",
    "cloud architect",
    "data engineer",
    "data scientist",
    "machine learning engineer",
    "AI engineer",
    "mobile developer (iOS)",
    "mobile developer (Android)",
    "cross-platform mobile developer",
    "flutter developer",
    "react native developer",
    "game developer",
    "unity developer",
    "unreal engine developer",
    "embedded systems engineer",
    "firmware engineer",
    "hardware engineer",
    "robotics engineer",
    "AR/VR developer",
    "computer vision engineer",
    "NLP engineer",
    "blockchain developer",
    "solidity developer",
    "smart contract developer",
    "web3 developer",
    "security engineer",
    "cybersecurity engineer",
    "penetration tester",
    "application security engineer",
    "network engineer",
    "network architect",
    "systems administrator",
    "database administrator (DBA)",
    "database developer",
    "data warehouse engineer",
    "ETL developer",
    "business intelligence developer",
    "QA engineer",
    "test automation engineer",
    "performance engineer",
    "release engineer",
    "platform engineer",
    "infrastructure engineer",
    "site reliability engineer",
    "migration engineer",
    "API developer",
    "integration engineer",
    "kubernetes administrator",
    "salesforce developer",
   "IoT engineer",
   "MLOps engineer",
    "CRM developer",
    "ERP developer",
    "low-code/no-code developer",
    "generative AI engineer",
    "mainframe developer",
    "legacy systems engineer",
    "accessibility engineer",
    "UX/UI designer",
    "developer advocate",
    "technical evangelist",
    "solution architect",
    "enterprise architect",
    "software architect",
    "tech lead",
    "staff engineer",
    "principal engineer",
    "distinguished engineer"
];